# site settings
title: Pao Pro
subtitle: # by HTML5 UP
email: paolaramirez09@gmail.com
description: This is a site to showcase my professional online journey towards a development career and my projects
baseurl: "/pao_pro" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Herndon
state: VA <br></br>
zip_code: 
country: United States of America
phone: (305)699-8563

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/paolaramirez09
gitlab_url: # https://gitlab.com/andrewbanchich
googleplus_url: # https://plus.google.com/u/0/+AndrewBanchich
instagram_url: 
linkedin_url: https://www.linkedin.com/in/paola-ramirez0101/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
